### ISSUE TITLE
auto detection

### ISSUE THREAD

**Issue by tikismoke** [fritz-smh/domogik-plugin-ping#1] opened 2015-10-21 20:05 UTC
On my container (wheezy very light)  python-nmap was install and no error or warning as the lib/ping.py should show in xplplugin_ping.log.
Changed the ip range to my acord my lan but no host discovered.

Test in cli :
root@domogik0:~# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import nmap
> > > nm = nmap.PortScanner()
> > > nm.scan(hosts='192.168.1.0/24', arguments='-n -sP')
> > > {'nmap': {'scanstats': {'uphosts': '5', 'timestr': 'Wed Oct 21 22:03:31 2015', 'downhosts': '251', 'totalhosts': '256', 'elapsed': '6.85'}, 'scaninfo': {}, 'command_line': 'nmap -oX - -n -sP 192.168.1.0/24'}, 'scan': {'192.168.1.88': {'status': {'state': 'up', 'reason': 'echo-reply'}, 'hostnames': [], 'vendor': {}, 'addresses': {'ipv4': '192.168.1.88'}}, '192.168.1.93': {'status': {'state': 'up', 'reason': 'echo-reply'}, 'hostnames': [], 'vendor': {}, 'addresses': {'ipv4': '192.168.1.93'}}, '192.168.1.66': {'status': {'state': 'up', 'reason': 'echo-reply'}, 'hostnames': [], 'vendor': {}, 'addresses': {'ipv4': '192.168.1.66'}}, '192.168.1.105': {'status': {'state': 'up', 'reason': 'echo-reply'}, 'hostnames': [], 'vendor': {}, 'addresses': {'ipv4': '192.168.1.105'}}, '192.168.1.1': {'status': {'state': 'up', 'reason': 'echo-reply'}, 'hostnames': [], 'vendor': {}, 'addresses': {'ipv4': '192.168.1.1'}}}}
> > > nm.scan(hosts='192.168.0.0/24', arguments='-n -sP')
> > > {'nmap': {'scanstats': {'uphosts': '34', 'timestr': 'Wed Oct 21 22:03:47 2015', 'downhosts': '222', 'totalhosts': '256', 'elapsed': '1.99'}, 'scaninfo': {}, 'command_line': 'nmap -oX - -n -sP 192.168.0.0/24'}, 'scan': {'192.168.0.40': {'status': {'state': 'up', 'reason': 'arp-response'}, 'hostnames': [], 'vendor': {}, 'addresses': {'mac': '00:FF:AA:00:00:20', 'ipv4': '192.168.0.40'}}, '192.168.0.58': {'status': {'state': 'up', 'reason': 'arp-response'}, 'hostnames': [], 'vendor': {'00:01:E3:AC:24:BD': 'Siemens AG'}, 'addresses': {'mac': '00:01:E3:AC:24:BD', 'ipv4': 
> > > etc etc

**Comment by tikismoke** [comment] 2015-10-21 20:11
got this in log when launching detection:
2015-10-21 22:10:35,687 domogik-ping DEBUG MQ Request received MQMessage(action=device.new.get, data='{}')
2015-10-21 22:10:35,687 domogik-ping INFO Client new devices request : MQMessage(action=device.new.get, data='{}')

**Comment by tikismoke** [comment] 2015-11-09 19:06
Still the same as before.
Lauuch in python is working but in the plugin not

**Comment by fritz-smh** [comment] 2015-11-09 19:34
can you show me the log file after startup ?

**Comment by tikismoke** [comment] 2015-11-09 19:40
http://pastebin.com/H9iVVndS

and a crash when launching a detection:
http://pastebin.com/me5eHEFh

**Comment by fritz-smh** [comment] 2015-11-10 09:06
I found the root cause.
It is not in the plugin. 
Closing this ticket.

https://github.com/domogik/domogik/issues/168

**Closed as completed by fritz-smh** 2015-11-10 09:06 UTC
